"""
Copyright (C) 2015-2016 Kinnay, MrRean, RoadrunnerWMC
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY Yannik Marchand ''AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Yannik Marchand BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation 
are those of the authors and should not be interpreted as representing
official policies, either expressed or implied, of Yannik Marchand.
"""
def description(confName):
    descs = {
        'RespawnPos': 'The location where one team \nrespawns.',
        'Fld_Crank00': 'The Urchin Underpass map.',
        'GachihokoRouteArea': 'A line for tower control. \nConnects two points.',
        'GachihokoTargetPoint': 'A point for tower control. \nThis is where a line connects.',
        'Obj_Tree00': 'A tree. It can be painted on.',
        'Obj_VictoryPoint': 'A point where one team wins. \nThe winning point for \nRainmaker and Tower Control.',
        'Obj_VictoryLift': 'The Tower! Bring it to the \nenemy goal to win!',
        'Obj_Windsock': 'A decoration. It blows in the \nwind.',
        'Obj_Bunker01': 'A bunker for protection!',
	'Brd_Sparrow00': 'A little bird for decoration.',
	'ScrambleBombFlower': 'The Rainmaker spawn point.',
	'StartPos': 'The normal player \nspawn point.',
	'Obj_Grass00': 'A decoration.',
	'PaintTargetArea': 'A Splat Zone for multiplayer.',
	'Obj_TreeBanana': 'A Banana Tree. It can be \npainted on.',
	'Obj_SighterTarget': 'A shootable target \nused in the shooting range.',
	'Obj_BigNamazu': 'The Big Zapfish. Used \nas a decoration.',
	'Obj_PlazaTrain': 'A Train used on the \nplaza for decoration',
	'Obj_PlazaAmiibo': 'The amiibo case used \non the plaza.',
	'Npc_Jerry00': 'A NPC used for decoration.',
	'Fld_Hiagari00': 'The Map model for \nHiagari.',
	'GachihokoHikikomoriArea': 'The Rainmaker Free Zone \nused in multiplayer.',
	'Obj_JerryBeachBall': 'NPCs used for \ndecoration on hiagari.',
	'Obj_JerryBikini': 'A NPC used for \ndecoration on hiagari.',
	'Obj_JerryWeddingRelative': 'A Jellyfish relative used\n for the wedding on \n Hiagari.',
	'Obj_JerryWeddingBride': 'A Jellyfish bride used \nfor the wedding on \nHiagari.',
	'Obj_JerryFloat_Bikini00': 'A NPC used for \ndecoration on Hiagari.',
	'Obj_JerryFloat_Bikini01': 'A NPC used for \ndecoration on Hiagari.',
	'Obj_JerryFloat_Nude01': 'A NPC used for \ndecoration on Hiagari.',
	'Obj_JerryFloat_Mat00': 'A NPC used for \ndecoration on Hiagari.',
	'Obj_QuarryBeltHoko': 'The first set of \nTransport Belts used \non Quarry',
	'Obj_QuarryBeltYagura': 'The second set of \nTransport Belts used \non Quarry',
	'Fld_Quarry00': 'The moving Platforms in Pivot.',
	'Obj_QuarryBBQSet': 'A BBQ set used for\n decoration on Quarry.',
	'Obj_QuarryFlag': 'A flag used for decoration\n on Quarry.',
	'Obj_GachiSignBoad': 'A sign used to \ninform players of\n a Rainmaker Zone.',
	'Fld_Tutorial00': 'The Map model for \nthe Tutorial Map.',
	'Obj_AirBall': 'A Air Balloon that\n can be shot.',
	'Obj_AutoWarpPoint': 'A target/destination \npoint for planned \nink jumps.',
	'Obj_WaterTank': 'A Water Tank used \nfor decoration.',
	'Obj_IkaSetB': 'A Statue Set used \nfor decoration.',
	'Obj_IkaSetA': 'A Statue Set used \nfor decoration.',
	'Fld_Pivot00': 'The Map model for \nQuarry.',
	'Lft_PivotDoor00': 'The moving Platforms in Pivot.',
	'Lft_PivotDoor01': 'The moving Platforms in Pivot.',
	'Obj_JerryArt': 'A NPC used for \ndecoration on Pivot.',
	'Obj_Bunker02': 'A bunker for protection!',
	'Lft_PivotDoor03': 'The moving Platforms in Pivot.',
	'Fld_SkatePark00': 'The Map model for \nSkatePark.',
	'Fld_Crank01': 'The updated \nMap model for \nCrank.',
	'Fld_Athletic00': 'The Map model for \nAthletic',
	'Fld_Maze00': 'The Map model for \nMaze',
	'Fld_Kaisou00': 'The Map model for \nKaisou.',
	'Fld_Tuzura00': 'The Map model for \nTuzura.',
	'Obj_Athletic00': 'A box used on \nAthletic.',
	'Obj_BalloonLightMDL': 'A light used for \ndecoration.',
	'Obj_kaisouBox': 'A box used on \nKaisou',
	'Obj_Athletic01': 'A wall used on \nAthletic',
	'Obj_AirWallKaisouSteelFrame': 'The bridge steel frame \nused on Kaisou.',
	'Enm_RailKing': 'The DJ Octavio \nboss enemy.',
	'Obj_Compass': 'A target for \nthe arrow pointing \nthe player to a \nmission goal.',
	'Npc_CommanderBind': 'Cpt. Cuttlefish \nhow he appears in the \n final boss fight.',
	'ExplanationTextObjLastBoss': 'Explanation Trigger(Boss)',
	'Obj_Goal': 'Boss Goal',
	'Enm_CylinderKing': 'Octonozzle(Boss)',
	'Obj_Sphere': 'A orb adding 1 to \nthe players sp currency.',
	'Obj_AncientDocument': 'An ancient scroll that \ncan be found in missions.',
	'Obj_TreeOrange': 'A orange tree used for decoration.',
	'Fld_World00': 'The Map model for \nthe SP hub.',
	'Obj_Gateway': 'A level entry for \nsingleplayer maps.',
	'Obj_Geyser': 'A ink geyser used \nin singleplayer.',
	'Obj_InkRail': 'A Ink Rail spawner used \nin singleplayer.',
	'Obj_RailKingPilotHouse': 'The glass bowl DJ Octavio \ncan be seen in after beating \n the singleplayer.',
	'Obj_PlazaIdolSpeakerA': 'A speaker that can be \nseen on the plaza while \na splatfest is running.',
	'Obj_PlazaIdolSpeakerB': 'A speaker that can be \nseen on the plaza while \na splatfest is running.',
        }
    return descs.get(confName, confName)
        
def SettingName(oldName):
    params = {
        }     
    return params.get(oldName, oldName)

def objectName(oldobjectName):
    objs = {
        'Brd_Sparrow00': 'Sparrow',
        'ScrambleBombFlower': 'Rainmaker',
        'RespawnPos': 'Respawn Position',
        'StartPos': 'Starting Position',
        'Obj_VictoryLift': 'Tower Control Tower',
        'PaintTargetArea': 'Splat Zone',
        'Obj_VictoryPoint': 'Victory Point',
        'Obj_Jerry00': 'Jellyfish',
        'GachihokoTargetPoint': 'Tower Control Point',
        'GachihokoRouteArea': 'Tower Control Line',
        'Obj_Tree00': 'Tree',
        'Obj_SeaGull': 'Seagull',
        'Obj_Windsock': 'Windsock',
        'Lft_HeavyCraneMachine': 'Saltspray Crane',
        'Obj_Flag': 'Flag',
        'Obj_AirDancer': 'Air Dancer',
        'Obj_Grass00': 'Grass',
        'Lft_Forklift': 'Forklift',
        'Obj_TreeBanana': 'Banana Tree',
        'ExplanationTextObj': 'Explanation Trigger',
        'SwitchAllDead': 'Extermination Switch',
	'Fld_Crank00': 'Crank Map Field(old)',
	'Obj_SighterTarget': 'Shooting Range Target',
	'Obj_BigNamazu': 'Big Zapfish',
	'Obj_PlazaTrain': 'Plaza Train',
	'Obj_PlazaAmiibo': 'Plaza Amiibo Case',
	'Npc_Jerry00': 'Jellyfish',
	'Fld_Hiagari00': 'Hiagari Map Field',
	'GachihokoHikikomoriArea': 'Rainmaker Free Zone',
	'Obj_JerryBeachBall': 'Beachball Jellyfish',
	'Obj_JerryBikini': 'Beach Jellyfish',
	'Obj_JerryWeddingRelative': 'Jellyfish Wedding Relative',
	'Obj_JerryWeddingBride': 'Jellyfish Wedding Bride',
	'Obj_JerryFloat_Bikini00': 'Pool Jellyfish 1',
	'Obj_JerryFloat_Bikini01': 'Pool Jellyfish 2',
	'Obj_JerryFloat_Nude01': 'Pool Jellyfish 3',
	'Obj_JerryFloat_Mat00': 'Pool Jellyfish 4',
	'Obj_QuarryBeltHoko': 'Quarry Transport Belt 1',
	'Obj_QuarryBeltYagura': 'Quarry Transport Belt 2',
	'Fld_Quarry00': 'Quarry Map Field',
	'Obj_QuarryBBQSet': 'BBQ Set',
	'Obj_QuarryFlag': 'Flag',
	'Obj_GachiSignBoad': 'Rainmaker Zone Sign',
	'Fld_Tutorial00': 'Tutorial Map Field',
	'Obj_AirBall': 'Air Balloon',
	'Obj_AutoWarpPoint': 'Warp Point',
	'Obj_WaterTank': 'Water Tank',
	'Obj_IkaSetB': 'Statue Set B',
	'Obj_IkaSetA': 'Statue Set A',
	'Fld_Pivot00': 'Pivot Map Field',
	'Lft_PivotDoor00': 'Pivot Moving PLatforms(small)',
	'Lft_PivotDoor01': 'Pivot Moving PLatforms(big)',
	'Obj_JerryArt': 'Art Jellyfish',
	'Obj_Bunker01': 'VS Bumper(small)',
	'Obj_Bunker02': 'VS Bumper(big)',
	'Lft_PivotDoor03': 'Pivot Moving PLatforms(mid)',
	'Fld_SkatePark00': 'Skatepark Map Field',
	'Fld_Crank01': 'Crank Map Field(new)',
	'Fld_Athletic00': 'Athletic Map Field(new)',
	'Fld_Maze00': 'Maze Map Field',
	'Fld_Kaisou00': 'Kaisou Map Field',
	'Fld_Tuzura00': 'Tuzura Map Field',
	'Obj_Athletic00': 'Athletic Map Box',
	'Obj_BalloonLightMDL': 'Balloon Light',
	'Obj_kaisouBox': 'Kaisou Box',
	'Obj_Athletic01': 'Athletic Map Wall',
	'Obj_AirWallKaisouSteelFrame': 'Kaisou Steel Frame',
	'Enm_RailKing': 'DJ Octavio(Boss)',
	'Obj_Compass': 'Mission Arrow Target',
	'Npc_CommanderBind': 'Cpt.Cuttlefish(Boss)',
	'ExplanationTextObjLastBoss': 'Explanation Trigger(Boss)',
	'Obj_Goal': 'Boss Goal',
	'Enm_CylinderKing': 'Octonozzle(Boss)',
	'Obj_Sphere': 'Power Egg',
	'Obj_AncientDocument': 'SP Scroll',
	'Obj_TreeOrange': 'Orange Tree',
	'Fld_World00': 'World Map Field',
	'Obj_Gateway': 'SP level entry',
	'Obj_Geyser': 'Ink Geyser',
	'Obj_InkRail': 'Ink Rail Spawner',
	'Obj_RailKingPilotHouse': 'Octavio glass bowl',
	'Obj_PlazaIdolSpeakerA': 'Splatfest Speaker A',
	'Obj_PlazaIdolSpeakerB': 'Splatfest Speaker B',
        }
    return objs.get(oldobjectName, oldobjectName)

def levelName(oldlevelName):
    maps = {    
        'Fld_Crank00_Vss': 'Urchin Underpass (VSS)',
        'Fld_Warehouse00_Vss': 'Walleye Warehouse (VSS)',
        'Fld_SeaPlant00_Vss': 'Saltspray Rig (VSS)',
        'Fld_UpDown00_Vss': 'Arowna Mall (VSS)',
        'Fld_SkatePark00_Vss': 'Blackbelly Skatepark (VSS)',
        'Fld_Athletic00_Vss': 'Camp Triggerfish (VSS)',
        'Fld_Amida00_Vss': 'Port Mackerel (VSS)',
        'Fld_Maze00_Vss': 'Kelp Dome (VSS)',
        'Fld_Tuzura00_Vss': 'Moray Towers (VSS)',
        'Fld_Ruins00_Vss': 'Bluefin Depot (VSS)',
        'Fld_ShootingRange_Shr': 'Shooting Range',
        'Fld_Office00_Vss': 'Ancho-V Games (VSS)',
        'Fld_Quarry00_Vss': 'Piranha Pit (VSS)',
        'Fld_Jyoheki00_Vss': 'Flounder Heights (VSS)',
        'Fld_Pivot00_Vss': 'Museum D\'Alfonsino (VSS)',
        'Fld_Hiagari00_Vss': 'Mahi-Mahi Resort (VSS)',
        'Fld_Kaisou00_Vss': 'Hammerhead Bridge (VSS)',
        'Fld_Crank00_Dul': 'Urchin Underpass (Dojo)',
        'Fld_Warehouse00_Dul': 'Walleye Warehouse (Dojo)',
        'Fld_SeaPlant00_Dul': 'Saltspray Rig (Dojo)',
        'Fld_UpDown00_Dul': 'Arowna Mall (Dojo)',
        'Fld_SkatePark00_Dul': 'Blackbelly Skatepark (Dojo)',
        'Fld_Tutorial00_Ttr': 'Tutorial Stage',
        'Fld_TutorialShow00_Ttr': 'Tutorial Duplicate...?',
        'Fld_World00_Wld': 'Octovalley Map',
        'Fld_Plaza00_Plz': 'Inkopolis',
        'Fld_EasyHide00_Msn': 'Octotrooper Hideout',
        'Fld_EasyClimb00_Msn': 'Lair of the Octoballs',
        'Fld_EasyJump00_Msn': 'Rise of the Octoscopers',
        'Fld_Geyser00_Msn': 'Gusher Gauntlet',
        'Fld_Sponge00_Msn': 'Floating Sponge Garden',
        'Fld_Propeller00_Msn': 'Propeller Lift Playground',
        'Fld_PaintingLift00_Msn': 'Spreader Splatfest',
        'Fld_RvlMaze00_Msn': 'Octoling Invasion',
        'Fld_OctZero00_Msn': 'Unidentified Flying Object',
        'Fld_InkRail00_Msn': 'Inkrail Skyscape',
        'Fld_Invisible00_Msn': 'Inkvisible Avenues',
        'Fld_Dozer00_Msn': 'Flooder Junkyard',
        'Fld_SlideLift00_Msn': 'Shifting Splatforms',
        'Fld_RvlSkatePark00_Msn': 'Octoling Assault',
        'Fld_OctRuins00_Msn': 'Undeniable Flying Object',
        'Fld_Propeller01_Msn': 'Propeller-Lift Fortress',
        'Fld_Charge00_Msn': 'Octosniper Ramparts',
        'Fld_PaintingLift01_Msn': 'Spinning Spreaders',
        'Fld_TurnLift00_Msn': 'Tumbling Splatforms',
        'Fld_RvlRuins00_Msn': 'Octoling Uprising',
        'Fld_OctCrank00_Msn': 'Undeniable Flying Object',
        'Fld_Trance00_Msn': 'Splat-Switch Revolution',
        'Fld_Sponge01_Msn': 'Spongy Observatory',
        'Fld_Fusya00_Msn': 'Pinwheel Power Plant',
        'Fld_Dozer01_Msn': 'Far-Flung Flooders',
        'Fld_RvlSeaPlant00_Msn': 'Octoling Onslaught',
        'Fld_OctSkatePark00_Msn': 'Unavoidable Flying Object',
        'Fld_BossStampKing_Bos_Msn': 'The Mighty Octostamp!',
        'Fld_BossCylinderKing_Bos_Msn': 'The Dreaded Octonozzle!',
        'Fld_BossBallKing_Bos_Msn': 'The Rampaging Octowhirl!',
        'Fld_BossMouthKing_Bos_Msn': 'The Ravenous Octomaw!',
        'Fld_BossRailKing_Bos_Msn': 'Enter the Octobot King!',
    }

    return maps.get(oldlevelName, oldlevelName)

def ReplaceModel(objName, gen):
    models = {
        'Enm_Rival00': 'Rival00',
        'RespawnPos': 'Obj_RespawnPlatform',
        }     
    return models.get(objName, objName)
